### ISSUE TITLE
Missing null check in many functions using FindAAS

### ISSUE THREAD

**Issue by wilterdinkrobert** [admin-shell-io/aasx-server#58]
In AasxHttpContextHelper.cs the `FindAAS` function is used in several places without checking if the return object is null.

For example:
```
var findAasReturn = this.FindAAS(aasid, context.Request.QueryString, context.Request.RawUrl);
if (findAasReturn.aas == null)
{
    context.Response.SendResponse(HttpStatusCode.NotFound, $"No AAS with idShort '{aasid}' found.");
    return;
}
```

If the AAS cannot be found, the FindAAS function either returns `null` directly or a `FindAasReturn.aas` which is null.

Due to the missing null check the REST server breaks:
`curl -v http://localhost:51310/aas/123`
Output:
```
> GET /aas/123 HTTP/1.1
> Host: localhost:51310
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 Ok
< Server: Grapevine/4.1.2.0
< Date: Mon, 08 Feb 2021 21:37:14 GMT
< Content-Length: 703
< 
Exception has been thrown by the target of an invocation.
<br>
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Grapevine.Server.Route.<>c__DisplayClass42_0.<ConvertMethodToFunc>b__1(IHttpContext context)
   at Grapevine.Server.Route.Invoke(IHttpContext context)
   at Grapevine.Server.Router.Route(IHttpContext context, IList`1 routing)
* Connection #0 to host localhost left intact
   at Grapevine.Server.Router.Route(Object state)
```

**Comment by aorzelskiGH** [comment]
Thank you for your input. I will try to check and improve it during one of the next development phases.

**Comment by juileetikekar** [comment]
This issue has been fixed in the new REST API support with ASP.NET. 
The new REST endpoint is : http://localhost:5001/
For example: Get All Asset Administration Shells:  http://localhost:5001/shells
Swagger documentation for these APIs can be found at : http://localhost:5001/swagger/index.html
